# command to install dependencies
install:
  - echo "Installation of MiniConda"
  - cd ~
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o ~/miniconda.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh; fi
  - bash ~/miniconda.sh -b -p $HOME/miniconda
  - echo ". ~/miniconda/etc/profile.d/conda.sh" >> ~/.bashrc
  - source ~/.bashrc
  - cd ~/build/neuropoly/axondeepseg
  
jobs:
  include:
    - stage: Basic install
      os: linux
      script:
        - yes | conda env create -f environment_Linux.yml -n ads_venv
        - conda activate ads_venv
        - pip install -e .
        - pip install python-coveralls  # Add me to install python-coveralls
        - pip install pre-commit 
        - pre-commit run --all-files
        - py.test . -v --cov AxonDeepSeg/ --cov-report term-missing
    - stage: Basic install
      os: osx
      script:
        - yes | conda env create -f environment_macOS.yml -n ads_venv
        - conda activate ads_venv
        - pip install -e .
        - pip install python-coveralls  # Add me to install python-coveralls
        - pip install pre-commit 
        - pre-commit run --all-files
        - py.test . -v --cov AxonDeepSeg/ --cov-report term-missing
after_success:
  - coveralls
