os:
  - linux
  - osx

language: python
python:
  - "3.7"

# command to install dependencies
install:

  - echo "Installation of MiniConda"
  - cd ~
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o ~/miniconda.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh; fi
  - bash ~/miniconda.sh -b -p $HOME/miniconda
  - echo ". ~/miniconda/etc/profile.d/conda.sh" >> ~/.bashrc
  - source ~/.bashrc
  - yes | conda create -n ads_venv python=3.7
  - conda activate ads_venv
  - echo "Installation of the repository"
  - cd /home/travis/build/neuropoly/axondeepseg
  - pip install -e .
  - pip install python-coveralls  # Add me to install python-coveralls
# command to run tests
script:
  - echo "Launch general integrity test"
  - py.test . -v --cov AxonDeepSeg/ --cov-report term-missing
  
jobs:
  include:
    - stage: Basic install
      script:
        - py.test . -v --cov AxonDeepSeg/ --cov-report term-missing
    - stage: FSLeyes install
      script: 
        - yes | conda install -c conda-forge fsleyes=0.33.1
        - py.test . -v --cov AxonDeepSeg/ --cov-report term-missing
after_success:
  - coveralls
