channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.11.0=py37hf985489_0
  - alabaster=0.7.12=py_0
  - albumentations=0.3.0=py_0
  - appnope=0.1.2=py37hf985489_1
  - argon2-cffi=20.1.0=py37hf967b71_2
  - astor=0.8.1=pyh9f0ad1d_0
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - babel=2.9.0=pyhd3deb0d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - backports.lzma=0.0.14=py37hcd8ae14_3
  - blas=2.108=openblas
  - blas-devel=3.9.0=8_openblas
  - bleach=3.3.0=pyh44b312d_0
  - brotlipy=0.7.0=py37hf967b71_1001
  - bzip2=1.0.8=hc929b4f_4
  - c-ares=1.17.1=h0d85af4_1
  - ca-certificates=2020.12.5=h033912b_0
  - cairo=1.16.0=h4ec454a_1007
  - cctools_osx-64=949.0.1=h6407bdd_20
  - certifi=2020.12.5=py37hf985489_1
  - cffi=1.14.5=py37h4d371b4_0
  - chardet=4.0.0=py37hf985489_1
  - clang=11.1.0=h694c41f_0
  - clang-11=11.1.0=default_he082bbe_0
  - clang_osx-64=11.1.0=hb91bd55_0
  - clangxx=11.1.0=default_he082bbe_0
  - clangxx_osx-64=11.1.0=h7e1b574_0
  - cloudpickle=1.6.0=py_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - compiler-rt=11.1.0=h654b07c_0
  - compiler-rt_osx-64=11.1.0=h8c5fa43_0
  - contextlib2=0.6.0.post1=py_0
  - coverage=5.5=py37h271585c_0
  - cryptography=3.4.4=py37ha1e1f9f_0
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py37hf967b71_3
  - dask-core=2021.3.0=pyhd8ed1ab_0
  - dataclasses=0.7=pyhb2cacf7_7
  - dbus=1.13.6=h0c50699_1
  - dcm2niix=1.0.20181114=h04f5b5a_1000
  - decorator=4.4.2=py_0
  - defusedxml=0.7.0=pyhd8ed1ab_0
  - docutils=0.16=py37hf985489_3
  - entrypoints=0.3=pyhd8ed1ab_1003
  - et_xmlfile=1.0.1=py_1001
  - expat=2.2.10=h1c7c35f_0
  - ffmpeg=4.3.1=hb787a4c_2
  - fontconfig=2.13.1=hd23ceaa_1004
  - freetype=2.10.4=h4cff582_1
  - fsleyes=0.33.1=py37hc8dfbb8_0
  - fsleyes-props=1.7.0=py_0
  - fsleyes-widgets=0.11.0=pyhd8ed1ab_0
  - fslpy=3.5.3=pyh050c7b8_0
  - gast=0.4.0=pyh9f0ad1d_0
  - geos=3.9.1=he49afe7_2
  - gettext=0.19.8.1=h7937167_1005
  - glib=2.66.7=he49afe7_1
  - glib-tools=2.66.7=he49afe7_1
  - gmp=6.2.1=h2e338ed_0
  - gnutls=3.6.13=h756fd2b_1
  - graphite2=1.3.13=h2e338ed_1001
  - grpcio=1.36.1=py37h87f55f7_0
  - h5py=2.10.0=nompi_py37h6d80030_105
  - harfbuzz=2.7.4=hf28d55f_0
  - hdf5=1.10.6=nompi_hc5d9132_1114
  - icu=68.1=h74dc148_0
  - idna=2.10=pyh9f0ad1d_0
  - imageio=2.9.0=py_0
  - imagesize=1.2.0=py_0
  - imgaug=0.4.0=py_1
  - importlib-metadata=3.7.0=py37hf985489_0
  - importlib_metadata=3.7.0=hd8ed1ab_0
  - indexed_gzip=1.4.0=py37h5380d2d_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - ipykernel=5.5.0=py37he01cfaa_1
  - ipython=7.21.0=py37he01cfaa_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.3=pyhd3deb0d_0
  - isodate=0.6.0=py_1
  - jasper=1.900.1=h636a363_1006
  - jdcal=1.4.1=py_0
  - jedi=0.18.0=py37hf985489_2
  - jinja2=2.11.3=pyh44b312d_0
  - jpeg=9d=hbcb3906_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter=1.0.0=py37hf985489_6
  - jupyter_client=6.1.11=pyhd8ed1ab_1
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.7.1=py37hf985489_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.0=pyhd8ed1ab_1
  - keras=2.3.1=py37_0
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - kiwisolver=1.3.1=py37h70f7d40_1
  - krb5=1.17.2=h60d9502_0
  - lame=3.100=h35c211d_1001
  - lcms2=2.12=h577c468_0
  - ld64_osx-64=530=he8994da_20
  - ldid=2.1.2=h7660a38_2
  - libblas=3.9.0=8_openblas
  - libcblas=3.9.0=8_openblas
  - libclang=11.1.0=default_he082bbe_0
  - libclang-cpp11.1=11.1.0=default_he082bbe_0
  - libcurl=7.75.0=h8ef9fac_0
  - libcxx=11.1.0=habf9029_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libffi=3.3=h046ec9c_2
  - libgfortran=5.0.0=9_3_0_h6c81a4c_19
  - libgfortran5=9.3.0=h6c81a4c_19
  - libglib=2.66.7=hd556434_1
  - libgpuarray=0.7.6=h0d85af4_1003
  - libiconv=1.16=haf1e3a3_0
  - liblapack=3.9.0=8_openblas
  - liblapacke=3.9.0=8_openblas
  - libllvm11=11.1.0=hd011deb_0
  - libnghttp2=1.43.0=h07e645a_0
  - libopenblas=0.3.12=openmp_h54245bb_1
  - libopencv=4.5.1=py37h2dd4c96_0
  - libpng=1.6.37=h7cec526_2
  - libpq=13.1=h052a64a_2
  - libprotobuf=3.15.5=hcf210ce_0
  - libsodium=1.0.18=hbcb3906_1
  - libspatialindex=1.9.3=h1c7c35f_3
  - libssh2=1.9.0=h8a08a2b_5
  - libtiff=4.2.0=h355d032_0
  - libwebp-base=1.2.0=hbcf498f_0
  - libxml2=2.9.10=h802ca4f_3
  - llvm-openmp=11.0.1=h7c73e74_0
  - llvm-tools=11.1.0=hd011deb_0
  - lz4-c=1.9.3=h046ec9c_0
  - mako=1.1.4=pyh44b312d_0
  - markdown=3.3.4=pyhd8ed1ab_0
  - markupsafe=1.1.1=py37hf967b71_3
  - matplotlib=3.3.4=py37hf985489_0
  - matplotlib-base=3.3.4=py37haa7e288_0
  - mistune=0.8.4=py37hf967b71_1003
  - more-itertools=8.7.0=pyhd8ed1ab_0
  - mpld3=0.5.2=pyhd3deb0d_0
  - mysql-common=8.0.23=h694c41f_1
  - mysql-libs=8.0.23=hbeb7981_1
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.0.7=py37hf985489_3
  - nbformat=5.1.2=pyhd8ed1ab_1
  - ncurses=6.2=h2e338ed_4
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - nettle=3.6=hedd7734_0
  - networkx=2.5=py_0
  - nibabel=3.2.1=pyhd8ed1ab_0
  - notebook=6.2.0=py37hf985489_0
  - nspr=4.29=hbc8d48c_1
  - nss=3.47=hc0980d9_0
  - numpy=1.20.1=py37ha9839cc_0
  - olefile=0.46=pyh9f0ad1d_1
  - openblas=0.3.12=openmp_hd4b4ca2_1
  - opencv=4.5.1=py37hf985489_0
  - openh264=2.1.1=hfd3ada9_0
  - openpyxl=3.0.6=pyhd8ed1ab_0
  - openssl=1.1.1j=hbcf498f_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.3=py37hff173d8_0
  - pandoc=2.11.4=h35c211d_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.1=pyhd8ed1ab_0
  - pathlib2=2.3.5=py37hf985489_3
  - pcre=8.44=hb1e8313_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.1.1=py37hd4e48bc_0
  - pip=21.0.1=pyhd8ed1ab_0
  - pixman=0.40.0=hbcb3906_0
  - pluggy=0.13.1=py37hf985489_4
  - prettytable=2.1.0=pyhd8ed1ab_0
  - progressbar2=3.53.1=pyh9f0ad1d_0
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.16=pyha770c72_0
  - prompt_toolkit=3.0.16=hd8ed1ab_0
  - protobuf=3.15.5=py37hd8d24ac_0
  - pthread-stubs=0.4=hc929b4f_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - py=1.10.0=pyhd3deb0d_0
  - py-opencv=4.5.1=py37he01cfaa_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pydicom=2.1.2=pyhd3deb0d_0
  - pygments=2.8.0=pyhd8ed1ab_0
  - pygpu=0.7.6=py37h9f9e6dc_1002
  - pyopengl=3.1.5=py_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pypubsub=4.0.3=py_0
  - pyqt=5.12.3=py37hf985489_7
  - pyqt-impl=5.12.3=py37h5ae2165_7
  - pyqt5-sip=4.19.18=py37h5ab9d7d_7
  - pyqtchart=5.12=py37h5ae2165_7
  - pyqtwebengine=5.12.1=py37h5ae2165_7
  - pyrsistent=0.17.3=py37hf967b71_2
  - pysocks=1.7.1=py37hf985489_3
  - pytest=6.2.2=py37hf985489_0
  - pytest-cov=2.11.1=pyh44b312d_0
  - python=3.7.10=h7728216_100_cpython
  - python-dateutil=2.8.1=py_0
  - python-utils=2.5.5=pyh44b312d_0
  - python.app=1.3=py37hf967b71_4
  - python_abi=3.7=1_cp37m
  - pytz=2021.1=pyhd8ed1ab_0
  - pywavelets=1.1.1=py37h37391d0_3
  - pyyaml=5.4.1=py37hf967b71_0
  - pyzmq=22.0.3=py37h8f778e5_1
  - qt=5.12.9=h126340a_4
  - qtconsole=5.0.2=pyhd8ed1ab_0
  - qtpy=1.9.0=py_0
  - raven=6.10.0=py_0
  - readline=8.0=h0678c8f_2
  - requests=2.25.1=pyhd3deb0d_0
  - rtree=0.9.7=py37hf13911c_1
  - scikit-image=0.14.2=py37h0a44026_1
  - scikit-learn=0.19.2=py37hebd9d1a_0
  - scipy=1.6.0=py37hc22aa43_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py37hf985489_3
  - shapely=1.7.1=py37h2c4361b_4
  - six=1.15.0=pyh9f0ad1d_0
  - snowballstemmer=2.1.0=pyhd8ed1ab_0
  - sphinx=3.5.2=pyhd8ed1ab_0
  - sphinx_rtd_theme=0.5.1=pyhd3deb0d_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - sqlite=3.34.0=h17101e1_0
  - tabulate=0.8.9=pyhd8ed1ab_0
  - tapi=1100.0.11=h9ce4665_0
  - tensorboard=1.13.1=py37_0
  - tensorflow=1.13.1=hfddd6c2_8
  - tensorflow-base=1.13.1=py37_8
  - tensorflow-estimator=1.13.0=py37h24bf2e0_0
  - termcolor=1.1.0=py_2
  - terminado=0.9.2=py37hf985489_0
  - testpath=0.4.4=py_0
  - theano=1.0.5=py37h54c7649_1
  - tk=8.6.10=h0419947_1
  - toml=0.10.2=pyhd8ed1ab_0
  - toolz=0.11.1=py_0
  - tornado=6.1=py37hf967b71_1
  - tqdm=4.59.0=pyhd8ed1ab_0
  - traitlets=5.0.5=py_0
  - trimesh=3.9.8=pyh44b312d_0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.26.3=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.36.2=pyhd3deb0d_0
  - widgetsnbextension=3.5.1=py37hf985489_4
  - wxnatpy=0.3.2=py_0
  - wxpython=4.1.1=py37h65de6b0_0
  - x264=1!161.3030=h35c211d_0
  - xnat=0.3.25=pyh9f0ad1d_0
  - xz=5.2.5=haf1e3a3_1
  - yaml=0.2.5=haf1e3a3_0
  - zeromq=4.3.4=h1c7c35f_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h7795811_1010
  - zstd=1.4.9=h582d3a0_0
  - pre-commit=2.10.0=py37hf985489_0
  - pip:
    - opencv-contrib-python==4.5.1.48
    - opencv-python-headless==4.5.1.48
prefix: /Users/mathieuboudreau/opt/anaconda3/envs/ads_new_4
